# Matrix Operations

In [1]:
import numpy as np

## Transpose
$C = A^{T}$

In [2]:
# define matrix
A = np.array([
[1, 2],
[3, 4],
[5, 6]])
print(A)

# calculate transpose
C = A.T
print(C)

[[1 2]
 [3 4]
 [5 6]]
[[1 3 5]
 [2 4 6]]


## Inverse
$AB = BA = I^{n}$

In [3]:
# define matrix
A = np.array([
[1.0, 2.0],
[3.0, 4.0]])
print(A)

# invert matrix
B = np.linalg.inv(A)
print(B)

# multiply A and B
I = A.dot(B)
print(I)

[[1. 2.]
 [3. 4.]]
[[-2.   1. ]
 [ 1.5 -0.5]]
[[1.00000000e+00 1.11022302e-16]
 [0.00000000e+00 1.00000000e+00]]


## Trace

3x3 Matrix

$tr(A) = a_{1,1} + a_{2,2} + a_{3,3}$

In [4]:
# define matrix
A = np.array([
[1, 2, 3],
[4, 5, 6],
[7, 8, 9]])
print(A)

# calculate trace
B = np.trace(A)
print(B)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
15


## Determinant
$det(A)$

In [5]:
# define matrix
A = np.array([
[9, 3, 2],
[1, 3, 7],
[4, 8, 6]])
print(A)

# calculate determinant
B = np.linalg.det(A)
print(B)

[[9 3 2]
 [1 3 7]
 [4 8 6]]
-284.0000000000003


In [6]:
# define matrix
A = np.array([
[9, 3, 2, 1],
[4, 5, 6, 3],
[9, 7, 6, 5],
[5, 4, 6, 7]])
print(A)

# calculate determinant
B = np.linalg.det(A)
print(B)

[[9 3 2 1]
 [4 5 6 3]
 [9 7 6 5]
 [5 4 6 7]]
-316.00000000000006


## Rank
$rank(A)$

In [7]:
# rank
v1 = np.array([1,2,3])
print(v1)
vr1 = np.linalg.matrix_rank(v1)
print(vr1)

# zero rank
v2 = np.array([0,0,0,0,0])
print(v2)
vr2 = np.linalg.matrix_rank(v2)
print(vr2)

[1 2 3]
1
[0 0 0 0 0]
0


In [8]:
# rank 0
M0 = np.array([
[0,0],
[0,0]])
print(M0)
mr0 = np.linalg.matrix_rank(M0)
print(mr0)

# rank 1
M1 = np.array([
[1,2],
[1,2]])
print(M1)
mr1 = np.linalg.matrix_rank(M1)
print(mr1)

# rank 2
M2 = np.array([
[1,2],
[3,4]])
print(M2)
mr2 = np.linalg.matrix_rank(M2)
print(mr2)

[[0 0]
 [0 0]]
0
[[1 2]
 [1 2]]
1
[[1 2]
 [3 4]]
2


<hr>

# Sparse Matrices

In [14]:
# sparse matrix
from scipy.sparse import csr_matrix

# create dense matrix
A = np.array([
[1, 0, 0, 1, 0, 0],
[0, 0, 2, 0, 0, 1],
[0, 0, 0, 2, 0, 0]])
print(A)

# convert to sparse matrix (CSR method)
S = csr_matrix(A)
print(S)

# reconstruct dense matrix
B = S.todense()
print(B)

[[1 0 0 1 0 0]
 [0 0 2 0 0 1]
 [0 0 0 2 0 0]]
  (0, 0)	1
  (0, 3)	1
  (1, 2)	2
  (1, 5)	1
  (2, 3)	2
[[1 0 0 1 0 0]
 [0 0 2 0 0 1]
 [0 0 0 2 0 0]]


In [23]:
# create dense matrix
A = np.array([
[1, 0, 0, 1, 0, 0],
[0, 0, 2, 0, 0, 1],
[0, 0, 0, 2, 0, 0]])
print(A)

# calculate sparsity
sparsity = 1.0 - np.count_nonzero(A) / A.size
print(sparsity)

[[1 0 0 1 0 0]
 [0 0 2 0 0 1]
 [0 0 0 2 0 0]]
0.7222222222222222
